name: CI • Lint

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-php

      - name: Validate Composer
        run: composer validate --strict

      - name: Laravel Pint
        run: ./vendor/bin/pint

      - name: Commit fixes
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: apply Laravel Pint"